apiVersion: v1
kind: Service
metadata:
  namespace: invoice
  labels:
    app: invoice
  name: invoice
spec:
  ports:
  
    - protocol: TCP
      port: 8000
      targetPort: 8000
   
   
  selector:
    app: invoice
  type: ClusterIP
